### ISSUE TITLE
[BUG] Writing to directory /.config/psysh is not allowed

### ISSUE THREAD

**Issue by gander** [theofidry/PsyshBundle#76]
```
 User Notice  User Notice: Writing to directory /.config/psysh is not allowed.
```

How to change it?

**Comment by gander** [comment]
For now, workaround:

```yaml
services:
    Psy\Configuration:
        calls:
            - [ setConfigDir, [ '/tmp/_psy-sh_' ] ]

```
