### ISSUE TITLE
Symfony 5.4 custom variables configuration

### ISSUE THREAD

**Issue by wayne530** [theofidry/PsyshBundle#77]
Are there any updated examples of how to configure custom variables when using slightly newer versions of Symfony, e.g. 5.4? The example provided in the documentation does not seem to work.

**Comment by wayne530** [comment]
n/m was able to get it to work by adding `config/packages/psysh.yaml` and adding the variables there. Would be nice to update the doc!

**Comment by allan-simon** [comment]
@wayne530  can you put your yaml file because I tried exactly the same thing and it does not work

**Comment by wayne530** [comment]
@allan-simon sure

```yaml
# config/packages/psysh.yaml
psysh:
    variables:
        foo: "bar"
        ...
```
